### PR TITLE
Updated NDK used to r23b

### PR DESCRIPTION
**Pull request by Over17**
Perl changes are not really relevant because the NDK is delivered by Stevedore.

### CODE REVIEW

**Review by todi1856 — APPROVED** [review]

**Review by aurimasc — COMMENTED** [review]
Maybe it's better to cleanup NDK from perl at all?
The reason I kept these downloads was due to requirement for latest SDK which was not available in Stevedore. Ideally, we should take all deps from Stevedore and kill the perl code entirely.

**Comment by Over17** [comment]
@aurimasc yeah currently Perl code won't download the NDK (but will the SDK and ancient play libraries). I didn't remove the code itself yet.

I can create an issue to clean up the perl script from getting dependencies, once someone has the time and motivation to do it

**Review by aurimasc — APPROVED** [review]

**Review by juliusmik — APPROVED** [review]
Yeah, we can switch to getting dependencies from stevedore as new SDK, NDK and JDK versions are uploaded now. But that can definitely be an independent task

**Comment by Over17** [comment]
Can't see an "issues" tab in this repo and don't have "settings" as well, wondering who's the admin.

**Comment by todi1856** [comment]
> Can't see an "issues" tab in this repo and don't have "settings" as well, wondering who's the admin.

the admin is @bitter ? :)

**Pull request merged**
